version: '3.9'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6772AlAd@
    volumes:
      - ./Db:/var/lib/postgresql/data